#!/bin/sh
BINDIR=$(dirname "$(readlink -fn "$0")")
cd "$BINDIR"
#exec java -Xms1024M -Xmx1024M -jar craftbukkit.jar -o true
#exec java -Xmx4096M -jar craftbukkit.jar -o true
#exec java -Xmx1024M -jar craftbukkit.jar -o true
exec java -Xmx1024M -cp craftbukkit.jar:clojure-1.5.1.jar org.bukkit.craftbukkit.Main -o true
