name: neocloft
main: io.github.ujihisa.Neocloft.ClojurePlugin
version: 1.0.0
website: http://ujihisa.blogspot.com
author: Tatsuhiro Ujihisa
description: ask @ujm
commands:
  neocloft:
    description: everything about neocloft
    usage: /neocloft [subcommand]
